### ISSUE TITLE
Separate MRI and CT pipeline and add Prep Pipeline

### ISSUE THREAD

**Issue by adam2392** [ncsl/seek#10]
It would be nice to just run the freesurfer/fsl commands on MRI and CT be allowed separately.

**Comment by adam2392** [comment]
To make sure all the data from dicoms, go through the same conversion step (e.g. BIDS first and rotation), add a PREP step that uses `mne-bids` to `write_anat`.

Also should perform rotation of the image to a hardcoded orientation. Similar to #8.

@TheBrainChain I believe, you suggested `RAS`?

**Comment by TheBrainChain** [comment]
@adam2392, I believe Freesurfer's normal output is LIP, but all the raw data we receive is in LPS. Since RAS is the neurological convention I would suggest that.

**Comment by adam2392** [comment]
Closed via #23
