### ISSUE TITLE
Docker and/or Singularity Container for Pipelines

### ISSUE THREAD

**Issue by adam2392** [ncsl/seek#15]
#### Describe the problem
Currently the pipelines to run require usage of various 3rd party softwares that might not be trivial to setup and install, such as FreeSurfer, FSL, Gawk, Blender, MRTrix3, etc.

#### Describe your solution
A docker container running the installation, so we can run all pipelines thru the container.

#### Describe possible alternatives
I think Docker is the best way to do this.

**Comment by adam2392** [comment]
A modularized docker container, could look like just a high-level docker container that pulls in images and adds the following commands:

1. FreeSurfer: https://hub.docker.com/r/freesurfer/freesurfer/
2. FSL: https://hub.docker.com/r/vistalab/fsl-v5.0/dockerfile
3. Blender: https://github.com/ikester/blender-docker
4. Add `sudo apt-get install -y gawk`
5. SPM12: https://github.com/spm/spm-docker/blob/master/octave/Dockerfile
6. Octave: https://wiki.octave.org/Octave_for_GNU/Linux

This way, we can axe certain dependencies when needed.

**Comment by TheBrainChain** [comment]
- [X] All of the above
- [ ] Silent install of matlab (only requiring user's file installation key from Mathworks)
- [ ] Setting env. variables

Tested on:
- [X] Linux (Ubuntu 18.04)
- [X] Windows (WSL2)
- [ ] Mac
